from . import hr_ext
from . import hr_employee
from . import hr_payscale
from . import allowances_deductions
from . import hr_inputs
from . import hr_gp_fund
from . import hr_payslips
from . import hr_payslip_cron
from . import hr_employee_payroll_status
from . import hr_employee_status_history
from . import hr_employee_backdate_arrears
from . import hr_employee_half_pay
from . import hr_payslip_batch
from . import hr_payslip_advice
from . import res_config_settings
