from . import wps
from . import hr_inputs_wizard
from . import gp_fund_statement_wiz
from . import gp_fund_wiz
from . import allowance_wiz
from . import deduction_wiz
from . import top_sheet_allowance_wiz
from . import top_sheet_deduction_wiz
from . import ministerial_staff_deduction
from . import promote_wiz
from . import employee_data_rep
from . import hr_data_import
from . import promote_bulk_wiz
from . import payslips_cron_wizard
