from . import hr_loan_pause_wiz
from . import hr_loan_reschedule_wiz
from . import hr_loan_interest_reschedule_wiz
from . import bulk_hr_loan_interest_reschedule_wiz
from . import hr_loan_waiveoff_wiz
from . import hr_loan_paid_wiz
from . import hr_supplementary_loan_wiz
from . import calc_guarantor_gratuity_wiz
from . import employee_payroll_status_update_wiz
