from . import employee_status_change_wiz
from . import employee_backdate_arrears_confirm_wiz
from . import bulk_employee_backdate_arrears_wiz
from . import generate_payslip_wiz
from . import hr_emp_salary_inputs_import_wizard
from . import hr_emp_salary_inputs_installments_wizard
from . import hr_emp_salary_allowances_addition_wizard
from . import hr_emp_salary_deductions_addition_wizard
from . import hr_emp_salary_allowances_expiry_wizard
from . import recompute_employee_contract_wiz
